[package]
name = "shaders"
version = "0.1.0"
edition = "2021"
authors = ["Embark <opensource@embark-studios.com>"]
license = "MIT OR Apache-2.0"

[lib]
crate-type = ["dylib"]

[dependencies]
spirv-std = { version = "0.4.0-alpha.12", features = ["glam"] }
